version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    environment:
      FLASK_ENV: development
    stop_grace_period: 3s  # Adjust the grace period as needed
    stop_signal: SIGINT  # Use SIGINT to allow graceful shutdown